- name: Copying checkboxio pipeline template for build job
  template:
    force: yes
    src: ../templates/checkboxio-pipeline.yml.j2
    dest: /home/{{ ansible_user }}/checkboxio-pipeline.yml

- name: Create jenkins build job checkbox.io using jenkins-job-builder
  command:
    cmd: jenkins-jobs --conf /home/{{ ansible_user }}/jenkins_jobs.ini --user {{ jenkins_username }} --password {{ jenkins_password }} update /home/{{ ansible_user }}/checkboxio-pipeline.yml
