---
- hosts: localhost
  become: yes
  gather_facts: no
  
  roles:
    - env-vars
    - dump-sql

- hosts: iTrust
  become: yes
  gather_facts: no
  
  roles:

    - java-install
    - env-vars
    - maven-install
    - update-system
    - mysql-install
    - update-mysql
    - tomcat-install