---
- name: Run the equivalent of "apt-get update"
  apt:
    update_cache: yes
- name: Install pip
  apt:
    pkg: python-pip
    state: present
- name: Install boto3
  command: pip install boto boto3 ansible
