---
# tasks file for tomcat-install
- name: Download tomcat server
  get_url:
    url: http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.0.M17/bin/apache-tomcat-9.0.0.M17.tar.gz
    dest: /home/{{ ansible_user }}/apache-tomcat-9.0.0.M17.tar.gz

- name: Untar the tomcat server
  unarchive:
    src: /home/{{ ansible_user }}/apache-tomcat-9.0.0.M17.tar.gz
    dest: /home/{{ ansible_user }}/
    remote_src: yes

- name: Setup default model
  template:
    src: ../templates/default-setup.xml.j2
    dest: "/home/{{ ansible_user }}/apache-tomcat-9.0.0.M17/conf/tomcat-users.xml"
    mode: 0500

- name: transfer war file
  copy: 
    src: /var/lib/jenkins/workspace/iTrust/iTrust2/target/iTrust2.war
    dest: /home/{{ ansible_user }}/apache-tomcat-9.0.0.M17/webapps/iTrust2.war

- name: Start Tomcat server
  shell: nohup sh /home/{{ ansible_user }}/apache-tomcat-9.0.0.M17/bin/startup.sh
