---
# tasks file for jenkins-job-builder-install
- name: Install pip
  apt:
    pkg: python-pip
    state: present

- name: Install Jenkins Job Builder.
  pip:
    name: jenkins-job-builder

- name: Ensure Jenkins Job Builder is installed.
  pip:
    name: jenkins-job-builder
    state: present
