---
# tasks file for pipeline/roles/env-vars
- name: Remove EC2 Key Pair
  ec2_key:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: us-east-2
    name: prod_key
    state: absent
- name: Create EC2 Key Pair
  ec2_key:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: us-east-2
    name: prod_key
    force: true
  register: ec2_key_result
- name: Save private key
  copy: content="{{ ec2_key_result.key.private_key }}" dest="/etc/ssh/aws_ec2.pem" mode=0400
