---
- hosts: checkbox
  become: yes
  gather_facts: no
  
  roles:
    - ping
    - env-vars
    - nodejs-install
    - mongodb-install
    - mongodb-configure
    - forever-install
    - setup-checkbox
    - setup-proxy