---
- name: Creating EC2 Ubuntu instance for iTrust
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    instance_type: t2.micro
    image: ami-0fc20dd1da406780b
    region: us-east-2
    key_name: prod_key
    group_id: sg-0bfd003365883a796
    count: 1
    wait: true
    instance_tags:
      Name: iTrust-prod
  register: ec2_iTrust

- name: Creating EC2 Ubuntu instance for checkbox.io
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    instance_type: t2.micro
    image: ami-0fc20dd1da406780b
    region: us-east-2
    key_name: prod_key
    group_id: sg-0bfd003365883a796
    count: 1
    wait: true
    instance_tags:
      Name: checkbox.io-prod
  register: ec2_checkbox

- name: Creating EC2 Ubuntu instance for Monitoring
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    instance_type: t2.micro
    image: ami-0fc20dd1da406780b
    region: us-east-2
    key_name: prod_key
    group_id: sg-0bfd003365883a796
    count: 1
    wait: true
    instance_tags:
      Name: monitor
  register: ec2_monitor

- name: Template a file to /etc/files.conf
  template:
    src: /bakerx/production/roles/ec2-instance/templates/inventory.ini.j2
    dest: /bakerx/inventory.ini

- name: Delete file Checkbox
  file:
    path: /bakerx/monitor/dashboard/metrics/checkbox.txt
    state: absent

- name: Create file Checkbox
  file:
    path: /bakerx/monitor/dashboard/metrics/checkbox.txt
    state: touch

- name: Delete file iTrust
  file:
    path: /bakerx/monitor/dashboard/metrics/itrust.txt
    state: absent

- name: Create file iTrust
  file:
    path: /bakerx/monitor/dashboard/metrics/itrust.txt
    state: touch

- name: Delete file monitor
  file:
    path: /bakerx/monitor/agent/monitor.txt
    state: absent

- name: Create file monitor
  file:
    path: /bakerx/monitor/agent/monitor.txt
    state: touch

- name: Copy checkbox.io ip address
  lineinfile:
    path: /bakerx/monitor/dashboard/metrics/checkbox.txt
    line: "{{ ec2_checkbox['instances'][0]['public_ip'] }}"

- name: Copy iTrust ip address
  lineinfile:
    path: /bakerx/monitor/dashboard/metrics/itrust.txt
    line: "{{ ec2_iTrust['instances'][0]['public_ip'] }}"

- name: Copy monitor ip address
  lineinfile:
    path: /bakerx/monitor/agent/monitor.txt
    line: "{{ ec2_monitor['instances'][0]['public_ip'] }}"
