---
- hosts: monitor
  become: yes
  gather_facts: no
  roles:
    - nodejs-install
    - forever-install
    - dashboard-setup
- hosts: checkbox.io
  become: yes
  gather_facts: no
  roles:
    - nodejs-install
    - forever-install
    - agent-setup
- hosts: iTrust
  become: yes
  gather_facts: no
  roles:
    - nodejs-install
    - forever-install
    - agent-setup
