---
# tasks file for nodejs-install
- name: Add apt key for nodesource
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add repo for nodesource
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_12.x xenial main'
    update_cache: yes

- name: Install nodejs
  apt: name=nodejs

- name: Ensure nodejs is installed.
  apt:
    name: nodejs
    state: present
